Admin.create(name: 'Admin Padrão', email: 'admin@admin.com', password: '123456', is_default: true, permission_level: "Administrador")
Admin.create(name: 'Admin Assistente', email: 'assistente@admin.com', password: '123456')
Offer.create(title: "Oferta 1", description: "Descrição da oferta 1", price: 100, created_by: "admin@admin.com")
Offer.create(title: "Oferta 2", description: "Descrição da oferta 2", price: 200, created_by: "admin@admin.com")
Offer.create(title: "Oferta 3", description: "Descrição da oferta 3", price: 300, created_by: "admin@admin.com")
Offer.create(title: "Oferta 4", description: "Descrição da oferta 4", price: 400, created_by: "admin@admin.com")
Offer.create(title: "Oferta 5", description: "Descrição da oferta 5", price: 500, created_by: "admin@admin.com")
Offer.create(title: "Oferta 6", description: "Descrição da oferta 6", price: 600, created_by: "admin@admin.com")
Offer.create(title: "Oferta 7", description: "Descrição da oferta 7", price: 700, created_by: "admin@admin.com")
Offer.create(title: "Oferta 8", description: "Descrição da oferta 8", price: 800, created_by: "admin@admin.com")
Offer.create(title: "Oferta 9", description: "Descrição da oferta 9", price: 900, created_by: "admin@admin.com")
Offer.create(title: "Oferta 10", description: "Descrição da oferta 10", price: 100, created_by: "admin@admin.com")
Offer.create(title: "Oferta 11", description: "Descrição da oferta 11", price: 100, created_by: "admin@admin.com")
Offer.create(title: "Oferta 12", description: "Descrição da oferta 12", price: 100, created_by: "admin@admin.com")
Offer.create(title: "Oferta 13", description: "Descrição da oferta 13", price: 100, created_by: "admin@admin.com")
Offer.create(title: "Oferta 14", description: "Descrição da oferta 14", price: 100, created_by: "admin@admin.com")
Offer.create(title: "Oferta 15", description: "Descrição da oferta 15", price: 100, created_by: "admin@admin.com")
Offer.create(title: "Oferta 16", description: "Descrição da oferta 16", price: 100, created_by: "admin@admin.com")
Offer.create(title: "Oferta 17", description: "Descrição da oferta 17", price: 100, created_by: "admin@admin.com")
Offer.create(title: "Oferta 18", description: "Descrição da oferta 18", price: 100, created_by: "admin@admin.com")
Offer.create(title: "Oferta 19", description: "Descrição da oferta 19", price: 100, created_by: "a9dmin@admin.com")
Offer.create(title: "Oferta 20", description: "Descrição da oferta 20", price: 100, created_by: "admin@admin.com")
Offer.create(title: "Oferta 21", description: "Descrição da oferta 21", price: 100, created_by: "admin@admin.com")
Offer.create(title: "Oferta 22", description: "Descrição da oferta 22", price: 100, created_by: "admin@admin.com")
Offer.create(title: "Oferta 23", description: "Descrição da oferta 23", price: 100, created_by: "admin@admin.com")